name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "$7Monopoly$$" | docker login --username vfcevallos --password-stdin
        docker image build -t vfcevallos/gitops1:hellov1.0 .
        docker push vfcevallos/gitops1:hellov1.0
